
'use client';

import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'en';
    setLanguage(savedLanguage);
  }, []);

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  // Comprehensive translation function
  const t = (key) => {
    const translations = {
      en: {
        // App & General
        app_name: 'AdminPro',
        user: 'User',
        email: 'Email',
        profile: 'Profile',
        user_profile: 'User Profile',
        sign_out: 'Sign Out',
        
        // Customizer
        customizer: 'Customizer',
        customizeOverview: 'Customize your dashboard',
        themeColors: 'Theme Colors',
        appearance: 'Appearance',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        sidebarPosition: 'Sidebar Position',
        left: 'Left',
        right: 'Right',
        bottom: 'Bottom',
        top: 'Top',
        language: 'Language',
        resetToDefaults: 'Reset to Defaults',

        // Main Navigation
        dashboard: 'Dashboard',
        users: 'Users',
        analytics: 'Analytics',
        products: 'Products',
        reports: 'Reports',
        messages: 'Messages',
        calendar: 'Calendar',
        security: 'Security',
        performance: 'Performance',
        settings: 'Settings',

        // Users Submenu
        all_users: 'All Users',
        add_user: 'Add User',
        active_users: 'Active Users',
        user_list: 'User List',
        user_activity: 'User Activity',
        user_permissions: 'User Permissions',
        single_user: 'Single User',
        bulk_import: 'Bulk Import',
        invite_users: 'Invite Users',
        online_now: 'Online Now',
        recent_activity: 'Recent Activity',
        engagement_stats: 'Engagement Stats',

        // Analytics Submenu
        trends: 'Trends',
        reports: 'Reports',
        real_time: 'Real Time',
        sales_trends: 'Sales Trends',
        user_trends: 'User Trends',
        product_trends: 'Product Trends',
        monthly_reports: 'Monthly Reports',
        quarterly_reports: 'Quarterly Reports',
        yearly_reports: 'Yearly Reports',
        live_users: 'Live Users',
        live_sales: 'Live Sales',
        system_health: 'System Health',

        // Products Submenu
        all_products: 'All Products',
        inventory: 'Inventory',
        categories: 'Categories',
        product_catalog: 'Product Catalog',
        best_sellers: 'Best Sellers',
        product_performance: 'Product Performance',
        stock_levels: 'Stock Levels',
        low_stock_alerts: 'Low Stock Alerts',
        inventory_reports: 'Inventory Reports',
        manage_categories: 'Manage Categories',
        add_category: 'Add Category',
        category_analytics: 'Category Analytics',

        // Reports Submenu
        sales_reports: 'Sales Reports',
        export: 'Export',
        import: 'Import',
        daily_sales: 'Daily Sales',
        monthly_sales: 'Monthly Sales',
        sales_forecast: 'Sales Forecast',
        export_csv: 'Export CSV',
        export_pdf: 'Export PDF',
        export_excel: 'Export Excel',
        import_data: 'Import Data',
        import_templates: 'Import Templates',
        import_history: 'Import History',

        // Messages Submenu
        inbox: 'Inbox',
        sent: 'Sent',
        archived: 'Archived',
        unread_messages: 'Unread Messages',
        team_messages: 'Team Messages',
        priority_messages: 'Priority Messages',
        recent_sent: 'Recent Sent',
        scheduled_messages: 'Scheduled Messages',
        delivery_status: 'Delivery Status',
        archived_conversations: 'Archived Conversations',
        archived_by_date: 'Archived by Date',
        archived_by_tags: 'Archived by Tags',

        // Calendar Submenu
        events: 'Events',
        schedule: 'Schedule',
        reminders: 'Reminders',
        upcoming_events: 'Upcoming Events',
        team_events: 'Team Events',
        create_event: 'Create Event',
        my_schedule: 'My Schedule',
        team_schedule: 'Team Schedule',
        time_blocks: 'Time Blocks',
        active_reminders: 'Active Reminders',
        recurring_reminders: 'Recurring Reminders',
        create_reminder: 'Create Reminder',

        // Security Submenu
        permissions: 'Permissions',
        api_keys: 'API Keys',
        audit_logs: 'Audit Logs',
        user_permissions: 'User Permissions',
        role_management: 'Role Management',
        access_control: 'Access Control',
        active_keys: 'Active Keys',
        generate_key: 'Generate Key',
        key_usage: 'Key Usage',
        system_logs: 'System Logs',
        user_activity: 'User Activity',
        security_events: 'Security Events',

        // Performance Submenu
        kras: 'KRAs',
        meetings: 'Meetings',
        feedback: 'Feedback',
        reviews: 'Reviews',
        skills: 'Skills',
        my_kras: 'My KRAs',
        team_kras: 'Team KRAs',
        kra_reports: 'KRA Reports',
        my_meetings: 'My Meetings',
        action_items: 'Action Items',
        agenda_templates: 'Agenda Templates',

        // Notifications
        notification_new_user: 'New user registered',
        notification_maintenance: 'Server maintenance scheduled',
        notification_backup: 'Backup completed successfully',

        // Actions & States
        message: 'Message',
        send: 'Send',
        archive: 'Archive',
        download: 'Download',
        upload: 'Upload',
        create: 'Create',
        manage: 'Manage',
        generate: 'Generate',
        export: 'Export',
        import: 'Import',
        view: 'View',
        edit: 'Edit',
        delete: 'Delete',
        save: 'Save',
        cancel: 'Cancel',
        apply: 'Apply',
        confirm: 'Confirm',
        search: 'Search',
        filter: 'Filter',
        sort: 'Sort',
        refresh: 'Refresh',
        loading: 'Loading',
        success: 'Success',
        error: 'Error',
        warning: 'Warning',
        info: 'Information'
      },
      es: {
        // App & General
        app_name: 'AdminPro',
        user: 'Usuario',
        email: 'Correo Electrónico',
        profile: 'Perfil',
        user_profile: 'Perfil de Usuario',
        sign_out: 'Cerrar Sesión',
        
        // Customizer
        customizer: 'Personalizador',
        customizeOverview: 'Personaliza tu panel',
        themeColors: 'Colores del Tema',
        appearance: 'Apariencia',
        darkMode: 'Modo Oscuro',
        lightMode: 'Modo Claro',
        sidebarPosition: 'Posición de la Barra Lateral',
        left: 'Izquierda',
        right: 'Derecha',
        bottom: 'Abajo',
        top: 'Arriba',
        language: 'Idioma',
        resetToDefaults: 'Restablecer a Predeterminados',

        // Main Navigation
        dashboard: 'Tablero',
        users: 'Usuarios',
        analytics: 'Análisis',
        products: 'Productos',
        reports: 'Informes',
        messages: 'Mensajes',
        calendar: 'Calendario',
        security: 'Seguridad',
        performance: 'Rendimiento',
        settings: 'Configuración',

        // Users Submenu
        all_users: 'Todos los Usuarios',
        add_user: 'Agregar Usuario',
        active_users: 'Usuarios Activos',
        user_list: 'Lista de Usuarios',
        user_activity: 'Actividad del Usuario',
        user_permissions: 'Permisos de Usuario',
        single_user: 'Usuario Individual',
        bulk_import: 'Importación Masiva',
        invite_users: 'Invitar Usuarios',
        online_now: 'En Línea Ahora',
        recent_activity: 'Actividad Reciente',
        engagement_stats: 'Estadísticas de Participación',

        // Analytics Submenu
        trends: 'Tendencias',
        reports: 'Informes',
        real_time: 'Tiempo Real',
        sales_trends: 'Tendencias de Ventas',
        user_trends: 'Tendencias de Usuarios',
        product_trends: 'Tendencias de Productos',
        monthly_reports: 'Informes Mensuales',
        quarterly_reports: 'Informes Trimestrales',
        yearly_reports: 'Informes Anuales',
        live_users: 'Usuarios en Vivo',
        live_sales: 'Ventas en Vivo',
        system_health: 'Estado del Sistema',

        // Products Submenu
        all_products: 'Todos los Productos',
        inventory: 'Inventario',
        categories: 'Categorías',
        product_catalog: 'Catálogo de Productos',
        best_sellers: 'Más Vendidos',
        product_performance: 'Rendimiento del Producto',
        stock_levels: 'Niveles de Stock',
        low_stock_alerts: 'Alertas de Stock Bajo',
        inventory_reports: 'Informes de Inventario',
        manage_categories: 'Gestionar Categorías',
        add_category: 'Agregar Categoría',
        category_analytics: 'Análisis de Categorías',

        // Reports Submenu
        sales_reports: 'Informes de Ventas',
        export: 'Exportar',
        import: 'Importar',
        daily_sales: 'Ventas Diarias',
        monthly_sales: 'Ventas Mensuales',
        sales_forecast: 'Pronóstico de Ventas',
        export_csv: 'Exportar CSV',
        export_pdf: 'Exportar PDF',
        export_excel: 'Exportar Excel',
        import_data: 'Importar Datos',
        import_templates: 'Plantillas de Importación',
        import_history: 'Historial de Importación',

        // Messages Submenu
        inbox: 'Bandeja de Entrada',
        sent: 'Enviados',
        archived: 'Archivados',
        unread_messages: 'Mensajes No Leídos',
        team_messages: 'Mensajes del Equipo',
        priority_messages: 'Mensajes Prioritarios',
        recent_sent: 'Enviados Recientes',
        scheduled_messages: 'Mensajes Programados',
        delivery_status: 'Estado de Entrega',
        archived_conversations: 'Conversaciones Archivadas',
        archived_by_date: 'Archivados por Fecha',
        archived_by_tags: 'Archivados por Etiquetas',

        // Calendar Submenu
        events: 'Eventos',
        schedule: 'Horario',
        reminders: 'Recordatorios',
        upcoming_events: 'Próximos Eventos',
        team_events: 'Eventos del Equipo',
        create_event: 'Crear Evento',
        my_schedule: 'Mi Horario',
        team_schedule: 'Horario del Equipo',
        time_blocks: 'Bloques de Tiempo',
        active_reminders: 'Recordatorios Activos',
        recurring_reminders: 'Recordatorios Recurrentes',
        create_reminder: 'Crear Recordatorio',

        // Security Submenu
        permissions: 'Permisos',
        api_keys: 'Claves API',
        audit_logs: 'Registros de Auditoría',
        user_permissions: 'Permisos de Usuario',
        role_management: 'Gestión de Roles',
        access_control: 'Control de Acceso',
        active_keys: 'Claves Activas',
        generate_key: 'Generar Clave',
        key_usage: 'Uso de Claves',
        system_logs: 'Registros del Sistema',
        user_activity: 'Actividad del Usuario',
        security_events: 'Eventos de Seguridad',

        // Performance Submenu
        kras: 'KRAs',
        meetings: 'Reuniones',
        feedback: 'Comentarios',
        reviews: 'Revisiones',
        skills: 'Habilidades',
        my_kras: 'Mis KRAs',
        team_kras: 'KRAs del Equipo',
        kra_reports: 'Informes KRA',
        my_meetings: 'Mis Reuniones',
        action_items: 'Elementos de Acción',
        agenda_templates: 'Plantillas de Agenda',

        // Notifications
        notification_new_user: 'Nuevo usuario registrado',
        notification_maintenance: 'Mantenimiento programado',
        notification_backup: 'Copia de seguridad completada',

        // Actions & States
        message: 'Mensaje',
        send: 'Enviar',
        archive: 'Archivar',
        download: 'Descargar',
        upload: 'Subir',
        create: 'Crear',
        manage: 'Gestionar',
        generate: 'Generar',
        export: 'Exportar',
        import: 'Importar',
        view: 'Ver',
        edit: 'Editar',
        delete: 'Eliminar',
        save: 'Guardar',
        cancel: 'Cancelar',
        apply: 'Aplicar',
        confirm: 'Confirmar',
        search: 'Buscar',
        filter: 'Filtrar',
        sort: 'Ordenar',
        refresh: 'Actualizar',
        loading: 'Cargando',
        success: 'Éxito',
        error: 'Error',
        warning: 'Advertencia',
        info: 'Información'
      },
      fr: {
        // App & General
        app_name: 'AdminPro',
        user: 'Utilisateur',
        email: 'Email',
        profile: 'Profil',
        user_profile: 'Profil Utilisateur',
        sign_out: 'Déconnexion',
        
        // Customizer
        customizer: 'Personnalisateur',
        customizeOverview: 'Personnalisez votre tableau de bord',
        themeColors: 'Couleurs du Thème',
        appearance: 'Apparence',
        darkMode: 'Mode Sombre',
        lightMode: 'Mode Clair',
        sidebarPosition: 'Position de la Barre Latérale',
        left: 'Gauche',
        right: 'Droite',
        bottom: 'Bas',
        top: 'Haut',
        language: 'Langue',
        resetToDefaults: 'Réinitialiser aux Valeurs par Défaut',

        // Main Navigation
        dashboard: 'Tableau de Bord',
        users: 'Utilisateurs',
        analytics: 'Analytique',
        products: 'Produits',
        reports: 'Rapports',
        messages: 'Messages',
        calendar: 'Calendrier',
        security: 'Sécurité',
        performance: 'Performance',
        settings: 'Paramètres',

        // Users Submenu
        all_users: 'Tous les Utilisateurs',
        add_user: 'Ajouter un Utilisateur',
        active_users: 'Utilisateurs Actifs',
        user_list: 'Liste des Utilisateurs',
        user_activity: 'Activité des Utilisateurs',
        user_permissions: 'Permissions des Utilisateurs',
        single_user: 'Utilisateur Unique',
        bulk_import: 'Importation en Masse',
        invite_users: 'Inviter des Utilisateurs',
        online_now: 'En Ligne Maintenant',
        recent_activity: 'Activité Récente',
        engagement_stats: 'Statistiques d\'Engagement',

        // Analytics Submenu
        trends: 'Tendances',
        reports: 'Rapports',
        real_time: 'Temps Réel',
        sales_trends: 'Tendances des Ventes',
        user_trends: 'Tendances des Utilisateurs',
        product_trends: 'Tendances des Produits',
        monthly_reports: 'Rapports Mensuels',
        quarterly_reports: 'Rapports Trimestriels',
        yearly_reports: 'Rapports Annuels',
        live_users: 'Utilisateurs en Direct',
        live_sales: 'Ventes en Direct',
        system_health: 'État du Système',

        // Products Submenu
        all_products: 'Tous les Produits',
        inventory: 'Inventaire',
        categories: 'Catégories',
        product_catalog: 'Catalogue de Produits',
        best_sellers: 'Meilleures Ventes',
        product_performance: 'Performance des Produits',
        stock_levels: 'Niveaux de Stock',
        low_stock_alerts: 'Alertes de Stock Faible',
        inventory_reports: 'Rapports d\'Inventaire',
        manage_categories: 'Gérer les Catégories',
        add_category: 'Ajouter une Catégorie',
        category_analytics: 'Analytique des Catégories',

        // Reports Submenu
        sales_reports: 'Rapports de Ventes',
        export: 'Exporter',
        import: 'Importer',
        daily_sales: 'Ventes Quotidiennes',
        monthly_sales: 'Ventes Mensuelles',
        sales_forecast: 'Prévisions des Ventes',
        export_csv: 'Exporter CSV',
        export_pdf: 'Exporter PDF',
        export_excel: 'Exporter Excel',
        import_data: 'Importer des Données',
        import_templates: 'Modèles d\'Importation',
        import_history: 'Historique d\'Importation',

        // Messages Submenu
        inbox: 'Boîte de Réception',
        sent: 'Envoyés',
        archived: 'Archivés',
        unread_messages: 'Messages Non Lus',
        team_messages: 'Messages d\'Équipe',
        priority_messages: 'Messages Prioritaires',
        recent_sent: 'Envoyés Récents',
        scheduled_messages: 'Messages Planifiés',
        delivery_status: 'Statut de Livraison',
        archived_conversations: 'Conversations Archivées',
        archived_by_date: 'Archivés par Date',
        archived_by_tags: 'Archivés par Étiquettes',

        // Calendar Submenu
        events: 'Événements',
        schedule: 'Planning',
        reminders: 'Rappels',
        upcoming_events: 'Événements à Venir',
        team_events: 'Événements d\'Équipe',
        create_event: 'Créer un Événement',
        my_schedule: 'Mon Planning',
        team_schedule: 'Planning d\'Équipe',
        time_blocks: 'Blocs de Temps',
        active_reminders: 'Rappels Actifs',
        recurring_reminders: 'Rappels Récurrents',
        create_reminder: 'Créer un Rappel',

        // Security Submenu
        permissions: 'Permissions',
        api_keys: 'Clés API',
        audit_logs: 'Journaux d\'Audit',
        user_permissions: 'Permissions Utilisateur',
        role_management: 'Gestion des Rôles',
        access_control: 'Contrôle d\'Accès',
        active_keys: 'Clés Actives',
        generate_key: 'Générer une Clé',
        key_usage: 'Utilisation des Clés',
        system_logs: 'Journaux Système',
        user_activity: 'Activité Utilisateur',
        security_events: 'Événements de Sécurité',

        // Performance Submenu
        kras: 'KRAs',
        meetings: 'Réunions',
        feedback: 'Retour',
        reviews: 'Revues',
        skills: 'Compétences',
        my_kras: 'Mes KRAs',
        team_kras: 'KRAs de l\'Équipe',
        kra_reports: 'Rapports KRA',
        my_meetings: 'Mes Réunions',
        action_items: 'Éléments d\'Action',
        agenda_templates: 'Modèles d\'Ordre du Jour',

        // Notifications
        notification_new_user: 'Nouvel utilisateur enregistré',
        notification_maintenance: 'Maintenance programmée',
        notification_backup: 'Sauvegarde terminée avec succès',

        // Actions & States
        message: 'Message',
        send: 'Envoyer',
        archive: 'Archiver',
        download: 'Télécharger',
        upload: 'Téléverser',
        create: 'Créer',
        manage: 'Gérer',
        generate: 'Générer',
        export: 'Exporter',
        import: 'Importer',
        view: 'Voir',
        edit: 'Modifier',
        delete: 'Supprimer',
        save: 'Sauvegarder',
        cancel: 'Annuler',
        apply: 'Appliquer',
        confirm: 'Confirmer',
        search: 'Rechercher',
        filter: 'Filtrer',
        sort: 'Trier',
        refresh: 'Actualiser',
        loading: 'Chargement',
        success: 'Succès',
        error: 'Erreur',
        warning: 'Avertissement',
        info: 'Information'
      },
      de: {
        // App & General
        app_name: 'AdminPro',
        user: 'Benutzer',
        email: 'E-Mail',
        profile: 'Profil',
        user_profile: 'Benutzerprofil',
        sign_out: 'Abmelden',
        
        // Customizer
        customizer: 'Anpassung',
        customizeOverview: 'Passen Sie Ihr Dashboard an',
        themeColors: 'Themenfarben',
        appearance: 'Erscheinungsbild',
        darkMode: 'Dunkler Modus',
        lightMode: 'Heller Modus',
        sidebarPosition: 'Seitenleistenposition',
        left: 'Links',
        right: 'Rechts',
        bottom: 'Unten',
        top: 'Oben',
        language: 'Sprache',
        resetToDefaults: 'Auf Standard zurücksetzen',

        // Main Navigation
        dashboard: 'Dashboard',
        users: 'Benutzer',
        analytics: 'Analytik',
        products: 'Produkte',
        reports: 'Berichte',
        messages: 'Nachrichten',
        calendar: 'Kalender',
        security: 'Sicherheit',
        performance: 'Leistung',
        settings: 'Einstellungen',

        // Users Submenu
        all_users: 'Alle Benutzer',
        add_user: 'Benutzer hinzufügen',
        active_users: 'Aktive Benutzer',
        user_list: 'Benutzerliste',
        user_activity: 'Benutzeraktivität',
        user_permissions: 'Benutzerberechtigungen',
        single_user: 'Einzelner Benutzer',
        bulk_import: 'Massenimport',
        invite_users: 'Benutzer einladen',
        online_now: 'Jetzt online',
        recent_activity: 'Aktuelle Aktivität',
        engagement_stats: 'Engagement-Statistiken',

        // Analytics Submenu
        trends: 'Trends',
        reports: 'Berichte',
        real_time: 'Echtzeit',
        sales_trends: 'Verkaufstrends',
        user_trends: 'Benutzertrends',
        product_trends: 'Produkttrends',
        monthly_reports: 'Monatliche Berichte',
        quarterly_reports: 'Vierteljährliche Berichte',
        yearly_reports: 'Jährliche Berichte',
        live_users: 'Live-Benutzer',
        live_sales: 'Live-Verkäufe',
        system_health: 'Systemstatus',

        // Products Submenu
        all_products: 'Alle Produkte',
        inventory: 'Inventar',
        categories: 'Kategorien',
        product_catalog: 'Produktkatalog',
        best_sellers: 'Bestseller',
        product_performance: 'Produktleistung',
        stock_levels: 'Bestandsniveaus',
        low_stock_alerts: 'Niedrige Bestandswarnungen',
        inventory_reports: 'Inventarberichte',
        manage_categories: 'Kategorien verwalten',
        add_category: 'Kategorie hinzufügen',
        category_analytics: 'Kategorieanalyse',

        // Reports Submenu
        sales_reports: 'Verkaufsberichte',
        export: 'Exportieren',
        import: 'Importieren',
        daily_sales: 'Tägliche Verkäufe',
        monthly_sales: 'Monatliche Verkäufe',
        sales_forecast: 'Verkaufsprognose',
        export_csv: 'CSV exportieren',
        export_pdf: 'PDF exportieren',
        export_excel: 'Excel exportieren',
        import_data: 'Daten importieren',
        import_templates: 'Importvorlagen',
        import_history: 'Importverlauf',

        // Messages Submenu
        inbox: 'Posteingang',
        sent: 'Gesendet',
        archived: 'Archiviert',
        unread_messages: 'Ungelesene Nachrichten',
        team_messages: 'Team-Nachrichten',
        priority_messages: 'Prioritätsnachrichten',
        recent_sent: 'Kürzlich gesendet',
        scheduled_messages: 'Geplante Nachrichten',
        delivery_status: 'Lieferstatus',
        archived_conversations: 'Archivierte Konversationen',
        archived_by_date: 'Nach Datum archiviert',
        archived_by_tags: 'Nach Tags archiviert',

        // Calendar Submenu
        events: 'Ereignisse',
        schedule: 'Zeitplan',
        reminders: 'Erinnerungen',
        upcoming_events: 'Bevorstehende Ereignisse',
        team_events: 'Team-Ereignisse',
        create_event: 'Ereignis erstellen',
        my_schedule: 'Mein Zeitplan',
        team_schedule: 'Team-Zeitplan',
        time_blocks: 'Zeitblöcke',
        active_reminders: 'Aktive Erinnerungen',
        recurring_reminders: 'Wiederkehrende Erinnerungen',
        create_reminder: 'Erinnerung erstellen',

        // Security Submenu
        permissions: 'Berechtigungen',
        api_keys: 'API-Schlüssel',
        audit_logs: 'Audit-Protokolle',
        user_permissions: 'Benutzerberechtigungen',
        role_management: 'Rollenverwaltung',
        access_control: 'Zugriffskontrolle',
        active_keys: 'Aktive Schlüssel',
        generate_key: 'Schlüssel generieren',
        key_usage: 'Schlüsselverwendung',
        system_logs: 'Systemprotokolle',
        user_activity: 'Benutzeraktivität',
        security_events: 'Sicherheitsereignisse',

        // Performance Submenu
        kras: 'KRAs',
        meetings: 'Besprechungen',
        feedback: 'Feedback',
        reviews: 'Bewertungen',
        skills: 'Fähigkeiten',
        my_kras: 'Meine KRAs',
        team_kras: 'Team-KRAs',
        kra_reports: 'KRA-Berichte',
        my_meetings: 'Meine Besprechungen',
        action_items: 'Aktionspunkte',
        agenda_templates: 'Agenda-Vorlagen',

        // Notifications
        notification_new_user: 'Neuer Benutzer registriert',
        notification_maintenance: 'Wartung geplant',
        notification_backup: 'Backup erfolgreich abgeschlossen',

        // Actions & States
        message: 'Nachricht',
        send: 'Senden',
        archive: 'Archivieren',
        download: 'Herunterladen',
        upload: 'Hochladen',
        create: 'Erstellen',
        manage: 'Verwalten',
        generate: 'Generieren',
        export: 'Exportieren',
        import: 'Importieren',
        view: 'Anzeigen',
        edit: 'Bearbeiten',
        delete: 'Löschen',
        save: 'Speichern',
        cancel: 'Abbrechen',
        apply: 'Anwenden',
        confirm: 'Bestätigen',
        search: 'Suchen',
        filter: 'Filtern',
        sort: 'Sortieren',
        refresh: 'Aktualisieren',
        loading: 'Lädt',
        success: 'Erfolg',
        error: 'Fehler',
        warning: 'Warnung',
        info: 'Information'
      }
    };
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, t, setLanguage: changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);